apiVersion: v1
entries:
  imagepuller:
  - apiVersion: v1
    appVersion: 0.1.1
    created: "2021-04-16T16:13:08.547264-04:00"
    description: Pull container images to your nodes so that they are already present when containers are launched.
    digest: a9313542850451bc22d1a7886ce6cc13ca4012ff754c87cc368c83d6c196534b
    name: imagepuller
    type: application
    urls:
    - https://helxplatform.github.io/kube-imagepuller/charts/imagepuller-0.1.1.tgz
    version: 0.1.1
generated: "2021-04-16T16:13:08.543775-04:00"
