image:
  repository: helxplatform/skopeo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 0.0.1

initPuller:
  args:
    - copy-images
    - "-i"
    - "from/this:tag"
    - "-i"
    - "from/that:tag"
    # - "--src-transport"
    # - "docker"
    # - "--src-prefix"
    # - "//index.docker.io/"
    # - "--dst-transport"
    # - "docker-daemon"
  secretMountPath: "/root"
  secretProjection: .docker/config.json
  pullSecret:
    enabled: false
    name: regcred
    key: .dockerconfigjson
